In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [80]:
path = '../data/star_classification.csv'

headernames = ['temperature', 'luminosity', 'radius', 'absolute_magn', 'star-type', 'star-color', 'Class']
dataset = pd.read_csv(path, names=headernames)
dataset.head()

temperature        luminosity        radius           absolute_magn  \
0  Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)   
1             3068            0.0024          0.17                   16.12   
2             3042            0.0005        0.1542                    16.6   
3             2600            0.0003         0.102                    18.7   
4             2800            0.0002          0.16                   16.65   

   star-type  star-color           Class  
0  Star type  Star color  Spectral Class  
1          0         Red               M  
2          0         Red               M  
3          0         Red               M  
4          0         Red               M

In [81]:
X = dataset.iloc[1:, :4].values
y = dataset.iloc[1:, -3].values


In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size
= 0.30)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [83]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 9)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [84]:
y_pred = classifier.predict(X_test)

In [85]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[12  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 11  0  0]
 [ 0  0  0  0 11  0]
 [ 0  0  0  0  0 12]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        11
           5       1.00      1.00      1.00        12

    accuracy                           1.00        72
   macro avg       1.00      1.00      1.00        72
weighted avg       1.00      1.00      1.00        72

Accuracy: 1.0
